title: Default Page

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Content
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Subpages
        templates:
          - default
      files:
        type: files
        label: Files
